In [7]:
import h5py
import numpy as np
import processing as pr

In [2]:
proposal = 2530
run = 50
module_number = 0
pattern = ['image', 'dark'] * 99 + ['end_image']

module = pr.Module(proposal=proposal, run=run, module=module_number, pattern=pattern)

In [3]:
a = module.process_frames(frame_type='dark', train_indices=range(10))#, dirname='processed_runs_xgm')

[[[[82 88 76 ... 66 63 75]
   [77 84 81 ... 73 76 66]
   [89 77 75 ... 78 65 72]
   ...
   [69 60 62 ... 76 88 75]
   [70 72 74 ... 63 82 77]
   [72 77 70 ... 78 85 76]]]


 [[[81 87 77 ... 66 62 75]
   [78 84 81 ... 73 75 65]
   [89 77 74 ... 77 65 72]
   ...
   [69 60 63 ... 76 88 76]
   [71 73 75 ... 63 81 77]
   [72 77 69 ... 77 85 75]]]


 [[[81 87 76 ... 66 63 74]
   [79 84 81 ... 73 76 66]
   [89 77 75 ... 78 65 72]
   ...
   [69 60 63 ... 77 87 75]
   [70 72 73 ... 64 80 77]
   [72 76 70 ... 77 84 76]]]


 ...


 [[[79 86 76 ... 65 61 73]
   [77 83 79 ... 72 74 63]
   [87 76 74 ... 77 63 70]
   ...
   [67 59 61 ... 73 85 72]
   [69 70 73 ... 61 78 73]
   [71 76 68 ... 74 82 72]]]


 [[[80 88 77 ... 65 61 73]
   [77 82 80 ... 72 75 64]
   [87 75 74 ... 77 63 70]
   ...
   [67 59 62 ... 73 85 73]
   [68 70 73 ... 61 78 75]
   [71 77 69 ... 75 82 72]]]


 [[[80 87 76 ... 65 63 73]
   [78 83 81 ... 72 75 65]
   [88 77 76 ... 78 64 71]
   ...
   [69 60 63 ... 74 86 73]
   [69 71 74 

In [9]:
np.squeeze(a.shape)

array([ 99,   1, 128, 512])

In [ ]:
module.process_frames(frame_type='images', train_indices=range(10), dirname='processed_runs_xgm')

In [ ]:
module.process_std(train_indices=range(10), dirname='processed_runs_xgm')

In [ ]:
module.process_normalised(dark_run=49, train_indices=range(100))#, dirname='processed_runs_xgm')

In [ ]:
111*99

In [ ]:
filename = f'processed_runs_xgm/run_{run}/module_{module_number}_diff.h5'
with h5py.File(filename, 'r') as f:
    data = f['data'][:] 
data

In [ ]:
data.max()

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(data.squeeze())